version: "3"

services:
  # Database
  dbdice:
    image: mysql:latest
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: gloria
      MYSQL_PASSWORD: contrasena
      MYSQL_DATABASE: sprint6
    ports:
      - "3306:3306"
    networks:
      - mysql-network

networks:
  mysql-network:
