version: "3"

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dice_game_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-admin}

  #app:
  # build: .
  #ports:
  # - "3000:3000" # Exposem el port 3000 per al servidor d'aplicacions
  #depends_on:
  # - mysql
networks:
  mysql-phpmyadmin:

volumes:
  db_data:
