version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dice_game_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000" # Exposem el port 3000 per al servidor d'aplicacions
    depends_on:
      - mysql
