name: CI for Sprint6DiceGame

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Show directory content
      run: ls -la

    - name: Start Docker containers
      run: |
        cd server && docker-compose up -d

    - name: Install dependencies
      run: |
        npm install

    - name: Stop Docker containers
      run: |
        cd server && docker-compose down
